;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/3/22 15:23:46

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; All Classes (Gson 2.2.2 API) allclasses-frame.html
#define IDH_1001	1001	; All Classes (Gson 2.2.2 API) allclasses-noframe.html
#define IDH_1086	1086	; API Help (Gson 2.2.2 API) help-doc.html
#define IDH_1091	1091	; Class Hierarchy (Gson 2.2.2 API) overview-tree.html
#define IDH_1084	1084	; Constant Field Values (Gson 2.2.2 API) constant-values.html
#define IDH_1085	1085	; Deprecated List (Gson 2.2.2 API) deprecated-list.html
#define IDH_1088	1088	; Gson 2.2.2 API index.html
#define IDH_1087	1087	; Index (Gson 2.2.2 API) index-all.html
#define IDH_1090	1090	; Overview (Gson 2.2.2 API) overview-summary.html
#define IDH_1089	1089	; Overview List (Gson 2.2.2 API) overview-frame.html
#define IDH_1092	1092	; Serialized Form (Gson 2.2.2 API) serialized-form.html
#define IDH_1060	1060	; com.google.gson (Gson 2.2.2 API) com\google\gson\package-frame.html
#define IDH_1061	1061	; com.google.gson (Gson 2.2.2 API) com\google\gson\package-summary.html
#define IDH_1062	1062	; com.google.gson Class Hierarchy (Gson 2.2.2 API) com\google\gson\package-tree.html
#define IDH_1038	1038	; ExclusionStrategy (Gson 2.2.2 API) com\google\gson\ExclusionStrategy.html
#define IDH_1039	1039	; FieldAttributes (Gson 2.2.2 API) com\google\gson\FieldAttributes.html
#define IDH_1040	1040	; FieldNamingPolicy (Gson 2.2.2 API) com\google\gson\FieldNamingPolicy.html
#define IDH_1041	1041	; FieldNamingStrategy (Gson 2.2.2 API) com\google\gson\FieldNamingStrategy.html
#define IDH_1042	1042	; Gson (Gson 2.2.2 API) com\google\gson\Gson.html
#define IDH_1043	1043	; GsonBuilder (Gson 2.2.2 API) com\google\gson\GsonBuilder.html
#define IDH_1044	1044	; InstanceCreator (Gson 2.2.2 API) com\google\gson\InstanceCreator.html
#define IDH_1045	1045	; JsonArray (Gson 2.2.2 API) com\google\gson\JsonArray.html
#define IDH_1046	1046	; JsonDeserializationContext (Gson 2.2.2 API) com\google\gson\JsonDeserializationContext.html
#define IDH_1047	1047	; JsonDeserializer (Gson 2.2.2 API) com\google\gson\JsonDeserializer.html
#define IDH_1048	1048	; JsonElement (Gson 2.2.2 API) com\google\gson\JsonElement.html
#define IDH_1049	1049	; JsonIOException (Gson 2.2.2 API) com\google\gson\JsonIOException.html
#define IDH_1050	1050	; JsonNull (Gson 2.2.2 API) com\google\gson\JsonNull.html
#define IDH_1051	1051	; JsonObject (Gson 2.2.2 API) com\google\gson\JsonObject.html
#define IDH_1052	1052	; JsonParseException (Gson 2.2.2 API) com\google\gson\JsonParseException.html
#define IDH_1053	1053	; JsonParser (Gson 2.2.2 API) com\google\gson\JsonParser.html
#define IDH_1054	1054	; JsonPrimitive (Gson 2.2.2 API) com\google\gson\JsonPrimitive.html
#define IDH_1055	1055	; JsonSerializationContext (Gson 2.2.2 API) com\google\gson\JsonSerializationContext.html
#define IDH_1056	1056	; JsonSerializer (Gson 2.2.2 API) com\google\gson\JsonSerializer.html
#define IDH_1057	1057	; JsonStreamParser (Gson 2.2.2 API) com\google\gson\JsonStreamParser.html
#define IDH_1058	1058	; JsonSyntaxException (Gson 2.2.2 API) com\google\gson\JsonSyntaxException.html
#define IDH_1059	1059	; LongSerializationPolicy (Gson 2.2.2 API) com\google\gson\LongSerializationPolicy.html
#define IDH_1082	1082	; TypeAdapter (Gson 2.2.2 API) com\google\gson\TypeAdapter.html
#define IDH_1083	1083	; TypeAdapterFactory (Gson 2.2.2 API) com\google\gson\TypeAdapterFactory.html
#define IDH_1063	1063	; Uses of Package com.google.gson (Gson 2.2.2 API) com\google\gson\package-use.html
#define IDH_1007	1007	; com.google.gson.annotations (Gson 2.2.2 API) com\google\gson\annotations\package-frame.html
#define IDH_1008	1008	; com.google.gson.annotations (Gson 2.2.2 API) com\google\gson\annotations\package-summary.html
#define IDH_1009	1009	; com.google.gson.annotations Class Hierarchy (Gson 2.2.2 API) com\google\gson\annotations\package-tree.html
#define IDH_1006	1006	; Expose (Gson 2.2.2 API) com\google\gson\annotations\Expose.html
#define IDH_1011	1011	; SerializedName (Gson 2.2.2 API) com\google\gson\annotations\SerializedName.html
#define IDH_1012	1012	; Since (Gson 2.2.2 API) com\google\gson\annotations\Since.html
#define IDH_1013	1013	; Until (Gson 2.2.2 API) com\google\gson\annotations\Until.html
#define IDH_1010	1010	; Uses of Package com.google.gson.annotations (Gson 2.2.2 API) com\google\gson\annotations\package-use.html
#define IDH_1002	1002	; Uses of Class com.google.gson.annotations.Expose (Gson 2.2.2 API) com\google\gson\annotations\class-use\Expose.html
#define IDH_1003	1003	; Uses of Class com.google.gson.annotations.SerializedName (Gson 2.2.2 API) com\google\gson\annotations\class-use\SerializedName.html
#define IDH_1004	1004	; Uses of Class com.google.gson.annotations.Since (Gson 2.2.2 API) com\google\gson\annotations\class-use\Since.html
#define IDH_1005	1005	; Uses of Class com.google.gson.annotations.Until (Gson 2.2.2 API) com\google\gson\annotations\class-use\Until.html
#define IDH_1015	1015	; Uses of Class com.google.gson.FieldAttributes (Gson 2.2.2 API) com\google\gson\class-use\FieldAttributes.html
#define IDH_1016	1016	; Uses of Class com.google.gson.FieldNamingPolicy (Gson 2.2.2 API) com\google\gson\class-use\FieldNamingPolicy.html
#define IDH_1018	1018	; Uses of Class com.google.gson.Gson (Gson 2.2.2 API) com\google\gson\class-use\Gson.html
#define IDH_1019	1019	; Uses of Class com.google.gson.GsonBuilder (Gson 2.2.2 API) com\google\gson\class-use\GsonBuilder.html
#define IDH_1021	1021	; Uses of Class com.google.gson.JsonArray (Gson 2.2.2 API) com\google\gson\class-use\JsonArray.html
#define IDH_1024	1024	; Uses of Class com.google.gson.JsonElement (Gson 2.2.2 API) com\google\gson\class-use\JsonElement.html
#define IDH_1025	1025	; Uses of Class com.google.gson.JsonIOException (Gson 2.2.2 API) com\google\gson\class-use\JsonIOException.html
#define IDH_1026	1026	; Uses of Class com.google.gson.JsonNull (Gson 2.2.2 API) com\google\gson\class-use\JsonNull.html
#define IDH_1027	1027	; Uses of Class com.google.gson.JsonObject (Gson 2.2.2 API) com\google\gson\class-use\JsonObject.html
#define IDH_1028	1028	; Uses of Class com.google.gson.JsonParseException (Gson 2.2.2 API) com\google\gson\class-use\JsonParseException.html
#define IDH_1029	1029	; Uses of Class com.google.gson.JsonParser (Gson 2.2.2 API) com\google\gson\class-use\JsonParser.html
#define IDH_1030	1030	; Uses of Class com.google.gson.JsonPrimitive (Gson 2.2.2 API) com\google\gson\class-use\JsonPrimitive.html
#define IDH_1033	1033	; Uses of Class com.google.gson.JsonStreamParser (Gson 2.2.2 API) com\google\gson\class-use\JsonStreamParser.html
#define IDH_1034	1034	; Uses of Class com.google.gson.JsonSyntaxException (Gson 2.2.2 API) com\google\gson\class-use\JsonSyntaxException.html
#define IDH_1035	1035	; Uses of Class com.google.gson.LongSerializationPolicy (Gson 2.2.2 API) com\google\gson\class-use\LongSerializationPolicy.html
#define IDH_1036	1036	; Uses of Class com.google.gson.TypeAdapter (Gson 2.2.2 API) com\google\gson\class-use\TypeAdapter.html
#define IDH_1014	1014	; Uses of Interface com.google.gson.ExclusionStrategy (Gson 2.2.2 API) com\google\gson\class-use\ExclusionStrategy.html
#define IDH_1017	1017	; Uses of Interface com.google.gson.FieldNamingStrategy (Gson 2.2.2 API) com\google\gson\class-use\FieldNamingStrategy.html
#define IDH_1020	1020	; Uses of Interface com.google.gson.InstanceCreator (Gson 2.2.2 API) com\google\gson\class-use\InstanceCreator.html
#define IDH_1022	1022	; Uses of Interface com.google.gson.JsonDeserializationContext (Gson 2.2.2 API) com\google\gson\class-use\JsonDeserializationContext.html
#define IDH_1023	1023	; Uses of Interface com.google.gson.JsonDeserializer (Gson 2.2.2 API) com\google\gson\class-use\JsonDeserializer.html
#define IDH_1031	1031	; Uses of Interface com.google.gson.JsonSerializationContext (Gson 2.2.2 API) com\google\gson\class-use\JsonSerializationContext.html
#define IDH_1032	1032	; Uses of Interface com.google.gson.JsonSerializer (Gson 2.2.2 API) com\google\gson\class-use\JsonSerializer.html
#define IDH_1037	1037	; Uses of Interface com.google.gson.TypeAdapterFactory (Gson 2.2.2 API) com\google\gson\class-use\TypeAdapterFactory.html
#define IDH_1065	1065	; com.google.gson.reflect (Gson 2.2.2 API) com\google\gson\reflect\package-frame.html
#define IDH_1066	1066	; com.google.gson.reflect (Gson 2.2.2 API) com\google\gson\reflect\package-summary.html
#define IDH_1067	1067	; com.google.gson.reflect Class Hierarchy (Gson 2.2.2 API) com\google\gson\reflect\package-tree.html
#define IDH_1069	1069	; TypeToken (Gson 2.2.2 API) com\google\gson\reflect\TypeToken.html
#define IDH_1068	1068	; Uses of Package com.google.gson.reflect (Gson 2.2.2 API) com\google\gson\reflect\package-use.html
#define IDH_1064	1064	; Uses of Class com.google.gson.reflect.TypeToken (Gson 2.2.2 API) com\google\gson\reflect\class-use\TypeToken.html
#define IDH_1078	1078	; com.google.gson.stream (Gson 2.2.2 API) com\google\gson\stream\package-frame.html
#define IDH_1079	1079	; com.google.gson.stream (Gson 2.2.2 API) com\google\gson\stream\package-summary.html
#define IDH_1080	1080	; com.google.gson.stream Class Hierarchy (Gson 2.2.2 API) com\google\gson\stream\package-tree.html
#define IDH_1074	1074	; JsonReader (Gson 2.2.2 API) com\google\gson\stream\JsonReader.html
#define IDH_1075	1075	; JsonToken (Gson 2.2.2 API) com\google\gson\stream\JsonToken.html
#define IDH_1076	1076	; JsonWriter (Gson 2.2.2 API) com\google\gson\stream\JsonWriter.html
#define IDH_1077	1077	; MalformedJsonException (Gson 2.2.2 API) com\google\gson\stream\MalformedJsonException.html
#define IDH_1081	1081	; Uses of Package com.google.gson.stream (Gson 2.2.2 API) com\google\gson\stream\package-use.html
#define IDH_1070	1070	; Uses of Class com.google.gson.stream.JsonReader (Gson 2.2.2 API) com\google\gson\stream\class-use\JsonReader.html
#define IDH_1071	1071	; Uses of Class com.google.gson.stream.JsonToken (Gson 2.2.2 API) com\google\gson\stream\class-use\JsonToken.html
#define IDH_1072	1072	; Uses of Class com.google.gson.stream.JsonWriter (Gson 2.2.2 API) com\google\gson\stream\class-use\JsonWriter.html
#define IDH_1073	1073	; Uses of Class com.google.gson.stream.MalformedJsonException (Gson 2.2.2 API) com\google\gson\stream\class-use\MalformedJsonException.html
