;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/4/11 20:09:01

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1318	1318	; HttpClient - authentication.html
#define IDH_1319	1319	; HttpClient - changelog-report.html
#define IDH_1320	1320	; HttpClient - charencodings.html
#define IDH_1321	1321	; HttpClient - cookies.html
#define IDH_1322	1322	; HttpClient - cvs-usage.html
#define IDH_1323	1323	; HttpClient - dependencies.html
#define IDH_1324	1324	; HttpClient - developer-activity-report.html
#define IDH_1325	1325	; HttpClient - developerguide.html
#define IDH_1326	1326	; HttpClient - downloads.html
#define IDH_1327	1327	; HttpClient - exception-handling.html
#define IDH_1328	1328	; HttpClient - features.html
#define IDH_1329	1329	; HttpClient - file-activity-report.html
#define IDH_1330	1330	; HttpClient - index.html
#define IDH_1331	1331	; HttpClient - issue-tracking.html
#define IDH_1332	1332	; HttpClient - javadoc-warnings-report.html
#define IDH_1333	1333	; HttpClient - javadoc.html
#define IDH_1334	1334	; HttpClient - jdepend-report.html
#define IDH_1335	1335	; HttpClient - junit-report.html
#define IDH_1336	1336	; HttpClient - license.html
#define IDH_1337	1337	; HttpClient - logging.html
#define IDH_1338	1338	; HttpClient - mail-lists.html
#define IDH_1339	1339	; HttpClient - maven-reports.html
#define IDH_1348	1348	; HttpClient - methods.html
#define IDH_1349	1349	; HttpClient - news.html
#define IDH_1350	1350	; HttpClient - overview.html
#define IDH_1351	1351	; HttpClient - performance.html
#define IDH_1352	1352	; HttpClient - preference-api.html
#define IDH_1353	1353	; HttpClient - project-info.html
#define IDH_1354	1354	; HttpClient - proposal.html
#define IDH_1355	1355	; HttpClient - redirects.html
#define IDH_1356	1356	; HttpClient - sslguide.html
#define IDH_1357	1357	; HttpClient - status.html
#define IDH_1358	1358	; HttpClient - task-list.html
#define IDH_1359	1359	; HttpClient - team-list.html
#define IDH_1360	1360	; HttpClient - threading.html
#define IDH_1361	1361	; HttpClient - troubleshooting.html
#define IDH_1362	1362	; HttpClient - tutorial.html
#define IDH_1363	1363	; HttpClient - userguide.html
#define IDH_1316	1316	; (HttpClient 3.1-alpha1 API) apidocs\packages.html
#define IDH_1000	1000	; All Classes (HttpClient 3.1-alpha1 API) apidocs\allclasses-frame.html
#define IDH_1001	1001	; All Classes (HttpClient 3.1-alpha1 API) apidocs\allclasses-noframe.html
#define IDH_1004	1004	; API Help (HttpClient 3.1-alpha1 API) apidocs\help-doc.html
#define IDH_1315	1315	; Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\overview-tree.html
#define IDH_1002	1002	; Constant Field Values (HttpClient 3.1-alpha1 API) apidocs\constant-values.html
#define IDH_1003	1003	; Deprecated List (HttpClient 3.1-alpha1 API) apidocs\deprecated-list.html
#define IDH_1006	1006	; HttpClient 3.1-alpha1 API apidocs\index.html
#define IDH_1005	1005	; Index (HttpClient 3.1-alpha1 API) apidocs\index-all.html
#define IDH_1313	1313	; Overview (HttpClient 3.1-alpha1 API) apidocs\overview-frame.html
#define IDH_1314	1314	; Overview (HttpClient 3.1-alpha1 API) apidocs\overview-summary.html
#define IDH_1317	1317	; Serialized Form (HttpClient 3.1-alpha1 API) apidocs\serialized-form.html
#define IDH_1049	1049	; ChunkedInputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ChunkedInputStream.html
#define IDH_1050	1050	; ChunkedOutputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ChunkedOutputStream.html
#define IDH_1051	1051	; CircularRedirectException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\CircularRedirectException.html
#define IDH_1102	1102	; ConnectionPoolTimeoutException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ConnectionPoolTimeoutException.html
#define IDH_1103	1103	; ConnectMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ConnectMethod.html
#define IDH_1104	1104	; ConnectTimeoutException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ConnectTimeoutException.html
#define IDH_1105	1105	; ContentLengthInputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ContentLengthInputStream.html
#define IDH_1136	1136	; Cookie (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\Cookie.html
#define IDH_1137	1137	; Credentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\Credentials.html
#define IDH_1138	1138	; DefaultHttpMethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\DefaultHttpMethodRetryHandler.html
#define IDH_1139	1139	; DefaultMethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\DefaultMethodRetryHandler.html
#define IDH_1140	1140	; Header (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\Header.html
#define IDH_1141	1141	; HeaderElement (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HeaderElement.html
#define IDH_1142	1142	; HeaderGroup (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HeaderGroup.html
#define IDH_1143	1143	; HostConfiguration (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HostConfiguration.html
#define IDH_1144	1144	; HttpClient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpClient.html
#define IDH_1145	1145	; HttpClientError (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpClientError.html
#define IDH_1146	1146	; HttpConnection (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpConnection.html
#define IDH_1147	1147	; HttpConnectionManager (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpConnectionManager.html
#define IDH_1148	1148	; HttpConstants (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpConstants.html
#define IDH_1149	1149	; HttpException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpException.html
#define IDH_1150	1150	; HttpHost (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpHost.html
#define IDH_1151	1151	; HttpMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpMethod.html
#define IDH_1152	1152	; HttpMethodBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpMethodBase.html
#define IDH_1153	1153	; HttpMethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpMethodRetryHandler.html
#define IDH_1154	1154	; HttpParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpParser.html
#define IDH_1155	1155	; HttpRecoverableException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpRecoverableException.html
#define IDH_1156	1156	; HttpState (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpState.html
#define IDH_1157	1157	; HttpStatus (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpStatus.html
#define IDH_1158	1158	; HttpsURL (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpsURL.html
#define IDH_1159	1159	; HttpURL (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpURL.html
#define IDH_1160	1160	; HttpVersion (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\HttpVersion.html
#define IDH_1161	1161	; InvalidRedirectLocationException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\InvalidRedirectLocationException.html
#define IDH_1162	1162	; MethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\MethodRetryHandler.html
#define IDH_1217	1217	; MultiThreadedHttpConnectionManager (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\MultiThreadedHttpConnectionManager.html
#define IDH_1218	1218	; NameValuePair (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\NameValuePair.html
#define IDH_1219	1219	; NoHttpResponseException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\NoHttpResponseException.html
#define IDH_1220	1220	; NTCredentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\NTCredentials.html
#define IDH_1221	1221	; org.apache.commons.httpclient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\package-frame.html
#define IDH_1222	1222	; org.apache.commons.httpclient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\package-summary.html
#define IDH_1223	1223	; org.apache.commons.httpclient Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\package-tree.html
#define IDH_1267	1267	; ProtocolException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ProtocolException.html
#define IDH_1269	1269	; ProxyClient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ProxyClient.html
#define IDH_1268	1268	; ProxyClient.ConnectResponse (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ProxyClient.ConnectResponse.html
#define IDH_1270	1270	; ProxyHost (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\ProxyHost.html
#define IDH_1271	1271	; RedirectException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\RedirectException.html
#define IDH_1272	1272	; SimpleHttpConnectionManager (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\SimpleHttpConnectionManager.html
#define IDH_1273	1273	; StatusLine (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\StatusLine.html
#define IDH_1275	1275	; URI (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\URI.html
#define IDH_1274	1274	; URI.DefaultCharsetChanged (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\URI.DefaultCharsetChanged.html
#define IDH_1276	1276	; URI.LocaleToCharsetMap (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\URI.LocaleToCharsetMap.html
#define IDH_1277	1277	; URIException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\URIException.html
#define IDH_1278	1278	; UsernamePasswordCredentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\UsernamePasswordCredentials.html
#define IDH_1224	1224	; Uses of Package org.apache.commons.httpclient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\package-use.html
#define IDH_1007	1007	; AuthChallengeException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthChallengeException.html
#define IDH_1008	1008	; AuthChallengeParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthChallengeParser.html
#define IDH_1009	1009	; AuthChallengeProcessor (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthChallengeProcessor.html
#define IDH_1010	1010	; AuthenticationException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthenticationException.html
#define IDH_1011	1011	; AuthPolicy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthPolicy.html
#define IDH_1012	1012	; AuthScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthScheme.html
#define IDH_1013	1013	; AuthSchemeBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthSchemeBase.html
#define IDH_1014	1014	; AuthScope (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthScope.html
#define IDH_1015	1015	; AuthState (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\AuthState.html
#define IDH_1016	1016	; BasicScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\BasicScheme.html
#define IDH_1036	1036	; CredentialsNotAvailableException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\CredentialsNotAvailableException.html
#define IDH_1037	1037	; CredentialsProvider (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\CredentialsProvider.html
#define IDH_1038	1038	; DigestScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\DigestScheme.html
#define IDH_1039	1039	; HttpAuthenticator (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\HttpAuthenticator.html
#define IDH_1040	1040	; HttpAuthRealm (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\HttpAuthRealm.html
#define IDH_1041	1041	; InvalidCredentialsException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\InvalidCredentialsException.html
#define IDH_1042	1042	; MalformedChallengeException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\MalformedChallengeException.html
#define IDH_1043	1043	; NTLMScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\NTLMScheme.html
#define IDH_1044	1044	; org.apache.commons.httpclient.auth (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\package-frame.html
#define IDH_1045	1045	; org.apache.commons.httpclient.auth (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\package-summary.html
#define IDH_1046	1046	; org.apache.commons.httpclient.auth Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\package-tree.html
#define IDH_1048	1048	; RFC2617Scheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\RFC2617Scheme.html
#define IDH_1047	1047	; Uses of Package org.apache.commons.httpclient.auth (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\package-use.html
#define IDH_1017	1017	; Uses of Class org.apache.commons.httpclient.auth.AuthChallengeException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthChallengeException.html
#define IDH_1018	1018	; Uses of Class org.apache.commons.httpclient.auth.AuthChallengeParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthChallengeParser.html
#define IDH_1019	1019	; Uses of Class org.apache.commons.httpclient.auth.AuthChallengeProcessor (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthChallengeProcessor.html
#define IDH_1020	1020	; Uses of Class org.apache.commons.httpclient.auth.AuthenticationException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthenticationException.html
#define IDH_1021	1021	; Uses of Class org.apache.commons.httpclient.auth.AuthPolicy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthPolicy.html
#define IDH_1023	1023	; Uses of Class org.apache.commons.httpclient.auth.AuthSchemeBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthSchemeBase.html
#define IDH_1024	1024	; Uses of Class org.apache.commons.httpclient.auth.AuthScope (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthScope.html
#define IDH_1025	1025	; Uses of Class org.apache.commons.httpclient.auth.AuthState (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthState.html
#define IDH_1026	1026	; Uses of Class org.apache.commons.httpclient.auth.BasicScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\BasicScheme.html
#define IDH_1027	1027	; Uses of Class org.apache.commons.httpclient.auth.CredentialsNotAvailableException (HttpClient 3.1-al apidocs\org\apache\commons\httpclient\auth\class-use\CredentialsNotAvailableException.html
#define IDH_1029	1029	; Uses of Class org.apache.commons.httpclient.auth.DigestScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\DigestScheme.html
#define IDH_1030	1030	; Uses of Class org.apache.commons.httpclient.auth.HttpAuthenticator (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\HttpAuthenticator.html
#define IDH_1031	1031	; Uses of Class org.apache.commons.httpclient.auth.HttpAuthRealm (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\HttpAuthRealm.html
#define IDH_1032	1032	; Uses of Class org.apache.commons.httpclient.auth.InvalidCredentialsException (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\auth\class-use\InvalidCredentialsException.html
#define IDH_1033	1033	; Uses of Class org.apache.commons.httpclient.auth.MalformedChallengeException (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\auth\class-use\MalformedChallengeException.html
#define IDH_1034	1034	; Uses of Class org.apache.commons.httpclient.auth.NTLMScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\NTLMScheme.html
#define IDH_1035	1035	; Uses of Class org.apache.commons.httpclient.auth.RFC2617Scheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\RFC2617Scheme.html
#define IDH_1022	1022	; Uses of Interface org.apache.commons.httpclient.auth.AuthScheme (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\AuthScheme.html
#define IDH_1028	1028	; Uses of Interface org.apache.commons.httpclient.auth.CredentialsProvider (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\auth\class-use\CredentialsProvider.html
#define IDH_1052	1052	; Uses of Class org.apache.commons.httpclient.ChunkedInputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ChunkedInputStream.html
#define IDH_1053	1053	; Uses of Class org.apache.commons.httpclient.ChunkedOutputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ChunkedOutputStream.html
#define IDH_1054	1054	; Uses of Class org.apache.commons.httpclient.CircularRedirectException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\CircularRedirectException.html
#define IDH_1055	1055	; Uses of Class org.apache.commons.httpclient.ConnectionPoolTimeoutException (HttpClient 3.1-alpha1 AP apidocs\org\apache\commons\httpclient\class-use\ConnectionPoolTimeoutException.html
#define IDH_1056	1056	; Uses of Class org.apache.commons.httpclient.ConnectMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ConnectMethod.html
#define IDH_1057	1057	; Uses of Class org.apache.commons.httpclient.ConnectTimeoutException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ConnectTimeoutException.html
#define IDH_1058	1058	; Uses of Class org.apache.commons.httpclient.ContentLengthInputStream (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ContentLengthInputStream.html
#define IDH_1059	1059	; Uses of Class org.apache.commons.httpclient.Cookie (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\Cookie.html
#define IDH_1061	1061	; Uses of Class org.apache.commons.httpclient.DefaultHttpMethodRetryHandler (HttpClient 3.1-alpha1 API apidocs\org\apache\commons\httpclient\class-use\DefaultHttpMethodRetryHandler.html
#define IDH_1062	1062	; Uses of Class org.apache.commons.httpclient.DefaultMethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\DefaultMethodRetryHandler.html
#define IDH_1063	1063	; Uses of Class org.apache.commons.httpclient.Header (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\Header.html
#define IDH_1064	1064	; Uses of Class org.apache.commons.httpclient.HeaderElement (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HeaderElement.html
#define IDH_1065	1065	; Uses of Class org.apache.commons.httpclient.HeaderGroup (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HeaderGroup.html
#define IDH_1066	1066	; Uses of Class org.apache.commons.httpclient.HostConfiguration (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HostConfiguration.html
#define IDH_1067	1067	; Uses of Class org.apache.commons.httpclient.HttpClient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpClient.html
#define IDH_1068	1068	; Uses of Class org.apache.commons.httpclient.HttpClientError (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpClientError.html
#define IDH_1069	1069	; Uses of Class org.apache.commons.httpclient.HttpConnection (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpConnection.html
#define IDH_1071	1071	; Uses of Class org.apache.commons.httpclient.HttpConstants (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpConstants.html
#define IDH_1072	1072	; Uses of Class org.apache.commons.httpclient.HttpException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpException.html
#define IDH_1073	1073	; Uses of Class org.apache.commons.httpclient.HttpHost (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpHost.html
#define IDH_1075	1075	; Uses of Class org.apache.commons.httpclient.HttpMethodBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpMethodBase.html
#define IDH_1077	1077	; Uses of Class org.apache.commons.httpclient.HttpParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpParser.html
#define IDH_1078	1078	; Uses of Class org.apache.commons.httpclient.HttpRecoverableException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpRecoverableException.html
#define IDH_1079	1079	; Uses of Class org.apache.commons.httpclient.HttpState (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpState.html
#define IDH_1080	1080	; Uses of Class org.apache.commons.httpclient.HttpStatus (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpStatus.html
#define IDH_1081	1081	; Uses of Class org.apache.commons.httpclient.HttpsURL (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpsURL.html
#define IDH_1082	1082	; Uses of Class org.apache.commons.httpclient.HttpURL (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpURL.html
#define IDH_1083	1083	; Uses of Class org.apache.commons.httpclient.HttpVersion (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpVersion.html
#define IDH_1084	1084	; Uses of Class org.apache.commons.httpclient.InvalidRedirectLocationException (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\class-use\InvalidRedirectLocationException.html
#define IDH_1086	1086	; Uses of Class org.apache.commons.httpclient.MultiThreadedHttpConnectionManager (HttpClient 3.1-alpha apidocs\org\apache\commons\httpclient\class-use\MultiThreadedHttpConnectionManager.html
#define IDH_1087	1087	; Uses of Class org.apache.commons.httpclient.NameValuePair (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\NameValuePair.html
#define IDH_1088	1088	; Uses of Class org.apache.commons.httpclient.NoHttpResponseException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\NoHttpResponseException.html
#define IDH_1089	1089	; Uses of Class org.apache.commons.httpclient.NTCredentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\NTCredentials.html
#define IDH_1090	1090	; Uses of Class org.apache.commons.httpclient.ProtocolException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ProtocolException.html
#define IDH_1092	1092	; Uses of Class org.apache.commons.httpclient.ProxyClient (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ProxyClient.html
#define IDH_1091	1091	; Uses of Class org.apache.commons.httpclient.ProxyClient.ConnectResponse (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ProxyClient.ConnectResponse.html
#define IDH_1093	1093	; Uses of Class org.apache.commons.httpclient.ProxyHost (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\ProxyHost.html
#define IDH_1094	1094	; Uses of Class org.apache.commons.httpclient.RedirectException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\RedirectException.html
#define IDH_1095	1095	; Uses of Class org.apache.commons.httpclient.SimpleHttpConnectionManager (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\SimpleHttpConnectionManager.html
#define IDH_1096	1096	; Uses of Class org.apache.commons.httpclient.StatusLine (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\StatusLine.html
#define IDH_1098	1098	; Uses of Class org.apache.commons.httpclient.URI (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\URI.html
#define IDH_1097	1097	; Uses of Class org.apache.commons.httpclient.URI.DefaultCharsetChanged (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\URI.DefaultCharsetChanged.html
#define IDH_1099	1099	; Uses of Class org.apache.commons.httpclient.URI.LocaleToCharsetMap (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\URI.LocaleToCharsetMap.html
#define IDH_1100	1100	; Uses of Class org.apache.commons.httpclient.URIException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\URIException.html
#define IDH_1101	1101	; Uses of Class org.apache.commons.httpclient.UsernamePasswordCredentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\UsernamePasswordCredentials.html
#define IDH_1060	1060	; Uses of Interface org.apache.commons.httpclient.Credentials (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\Credentials.html
#define IDH_1070	1070	; Uses of Interface org.apache.commons.httpclient.HttpConnectionManager (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpConnectionManager.html
#define IDH_1074	1074	; Uses of Interface org.apache.commons.httpclient.HttpMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpMethod.html
#define IDH_1076	1076	; Uses of Interface org.apache.commons.httpclient.HttpMethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\HttpMethodRetryHandler.html
#define IDH_1085	1085	; Uses of Interface org.apache.commons.httpclient.MethodRetryHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\class-use\MethodRetryHandler.html
#define IDH_1119	1119	; Cookie2 (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\Cookie2.html
#define IDH_1120	1120	; CookieAttributeHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookieAttributeHandler.html
#define IDH_1121	1121	; CookieOrigin (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookieOrigin.html
#define IDH_1122	1122	; CookiePathComparator (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookiePathComparator.html
#define IDH_1123	1123	; CookiePolicy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookiePolicy.html
#define IDH_1124	1124	; CookieSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookieSpec.html
#define IDH_1125	1125	; CookieSpecBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookieSpecBase.html
#define IDH_1126	1126	; CookieVersionSupport (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\CookieVersionSupport.html
#define IDH_1127	1127	; IgnoreCookiesSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\IgnoreCookiesSpec.html
#define IDH_1128	1128	; MalformedCookieException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\MalformedCookieException.html
#define IDH_1129	1129	; NetscapeDraftSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\NetscapeDraftSpec.html
#define IDH_1130	1130	; org.apache.commons.httpclient.cookie (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\package-frame.html
#define IDH_1131	1131	; org.apache.commons.httpclient.cookie (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\package-summary.html
#define IDH_1132	1132	; org.apache.commons.httpclient.cookie Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\package-tree.html
#define IDH_1134	1134	; RFC2109Spec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\RFC2109Spec.html
#define IDH_1135	1135	; RFC2965Spec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\RFC2965Spec.html
#define IDH_1133	1133	; Uses of Package org.apache.commons.httpclient.cookie (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\package-use.html
#define IDH_1106	1106	; Uses of Class org.apache.commons.httpclient.cookie.Cookie2 (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\Cookie2.html
#define IDH_1108	1108	; Uses of Class org.apache.commons.httpclient.cookie.CookieOrigin (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\CookieOrigin.html
#define IDH_1109	1109	; Uses of Class org.apache.commons.httpclient.cookie.CookiePathComparator (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\CookiePathComparator.html
#define IDH_1110	1110	; Uses of Class org.apache.commons.httpclient.cookie.CookiePolicy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\CookiePolicy.html
#define IDH_1112	1112	; Uses of Class org.apache.commons.httpclient.cookie.CookieSpecBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\CookieSpecBase.html
#define IDH_1114	1114	; Uses of Class org.apache.commons.httpclient.cookie.IgnoreCookiesSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\IgnoreCookiesSpec.html
#define IDH_1115	1115	; Uses of Class org.apache.commons.httpclient.cookie.MalformedCookieException (HttpClient 3.1-alpha1 A apidocs\org\apache\commons\httpclient\cookie\class-use\MalformedCookieException.html
#define IDH_1116	1116	; Uses of Class org.apache.commons.httpclient.cookie.NetscapeDraftSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\NetscapeDraftSpec.html
#define IDH_1117	1117	; Uses of Class org.apache.commons.httpclient.cookie.RFC2109Spec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\RFC2109Spec.html
#define IDH_1118	1118	; Uses of Class org.apache.commons.httpclient.cookie.RFC2965Spec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\RFC2965Spec.html
#define IDH_1107	1107	; Uses of Interface org.apache.commons.httpclient.cookie.CookieAttributeHandler (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\cookie\class-use\CookieAttributeHandler.html
#define IDH_1111	1111	; Uses of Interface org.apache.commons.httpclient.cookie.CookieSpec (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\cookie\class-use\CookieSpec.html
#define IDH_1113	1113	; Uses of Interface org.apache.commons.httpclient.cookie.CookieVersionSupport (HttpClient 3.1-alpha1 A apidocs\org\apache\commons\httpclient\cookie\class-use\CookieVersionSupport.html
#define IDH_1163	1163	; ByteArrayRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\ByteArrayRequestEntity.html
#define IDH_1179	1179	; DeleteMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\DeleteMethod.html
#define IDH_1180	1180	; EntityEnclosingMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\EntityEnclosingMethod.html
#define IDH_1181	1181	; ExpectContinueMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\ExpectContinueMethod.html
#define IDH_1182	1182	; FileRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\FileRequestEntity.html
#define IDH_1183	1183	; GetMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\GetMethod.html
#define IDH_1184	1184	; HeadMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\HeadMethod.html
#define IDH_1185	1185	; InputStreamRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\InputStreamRequestEntity.html
#define IDH_1206	1206	; MultipartPostMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\MultipartPostMethod.html
#define IDH_1207	1207	; OptionsMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\OptionsMethod.html
#define IDH_1208	1208	; org.apache.commons.httpclient.methods (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\package-frame.html
#define IDH_1209	1209	; org.apache.commons.httpclient.methods (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\package-summary.html
#define IDH_1210	1210	; org.apache.commons.httpclient.methods Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\package-tree.html
#define IDH_1212	1212	; PostMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\PostMethod.html
#define IDH_1213	1213	; PutMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\PutMethod.html
#define IDH_1214	1214	; RequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\RequestEntity.html
#define IDH_1215	1215	; StringRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\StringRequestEntity.html
#define IDH_1216	1216	; TraceMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\TraceMethod.html
#define IDH_1211	1211	; Uses of Package org.apache.commons.httpclient.methods (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\package-use.html
#define IDH_1164	1164	; Uses of Class org.apache.commons.httpclient.methods.ByteArrayRequestEntity (HttpClient 3.1-alpha1 AP apidocs\org\apache\commons\httpclient\methods\class-use\ByteArrayRequestEntity.html
#define IDH_1165	1165	; Uses of Class org.apache.commons.httpclient.methods.DeleteMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\DeleteMethod.html
#define IDH_1166	1166	; Uses of Class org.apache.commons.httpclient.methods.EntityEnclosingMethod (HttpClient 3.1-alpha1 API apidocs\org\apache\commons\httpclient\methods\class-use\EntityEnclosingMethod.html
#define IDH_1167	1167	; Uses of Class org.apache.commons.httpclient.methods.ExpectContinueMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\ExpectContinueMethod.html
#define IDH_1168	1168	; Uses of Class org.apache.commons.httpclient.methods.FileRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\FileRequestEntity.html
#define IDH_1169	1169	; Uses of Class org.apache.commons.httpclient.methods.GetMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\GetMethod.html
#define IDH_1170	1170	; Uses of Class org.apache.commons.httpclient.methods.HeadMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\HeadMethod.html
#define IDH_1171	1171	; Uses of Class org.apache.commons.httpclient.methods.InputStreamRequestEntity (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\methods\class-use\InputStreamRequestEntity.html
#define IDH_1172	1172	; Uses of Class org.apache.commons.httpclient.methods.MultipartPostMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\MultipartPostMethod.html
#define IDH_1173	1173	; Uses of Class org.apache.commons.httpclient.methods.OptionsMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\OptionsMethod.html
#define IDH_1174	1174	; Uses of Class org.apache.commons.httpclient.methods.PostMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\PostMethod.html
#define IDH_1175	1175	; Uses of Class org.apache.commons.httpclient.methods.PutMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\PutMethod.html
#define IDH_1177	1177	; Uses of Class org.apache.commons.httpclient.methods.StringRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\StringRequestEntity.html
#define IDH_1178	1178	; Uses of Class org.apache.commons.httpclient.methods.TraceMethod (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\TraceMethod.html
#define IDH_1176	1176	; Uses of Interface org.apache.commons.httpclient.methods.RequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\class-use\RequestEntity.html
#define IDH_1186	1186	; ByteArrayPartSource (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\ByteArrayPartSource.html
#define IDH_1195	1195	; FilePart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\FilePart.html
#define IDH_1196	1196	; FilePartSource (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\FilePartSource.html
#define IDH_1197	1197	; MultipartRequestEntity (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\MultipartRequestEntity.html
#define IDH_1198	1198	; org.apache.commons.httpclient.methods.multipart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\package-frame.html
#define IDH_1199	1199	; org.apache.commons.httpclient.methods.multipart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\package-summary.html
#define IDH_1200	1200	; org.apache.commons.httpclient.methods.multipart Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\package-tree.html
#define IDH_1202	1202	; Part (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\Part.html
#define IDH_1203	1203	; PartBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\PartBase.html
#define IDH_1204	1204	; PartSource (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\PartSource.html
#define IDH_1205	1205	; StringPart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\StringPart.html
#define IDH_1201	1201	; Uses of Package org.apache.commons.httpclient.methods.multipart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\package-use.html
#define IDH_1187	1187	; Uses of Class org.apache.commons.httpclient.methods.multipart.ByteArrayPartSource (HttpClient 3.1-al apidocs\org\apache\commons\httpclient\methods\multipart\class-use\ByteArrayPartSource.html
#define IDH_1188	1188	; Uses of Class org.apache.commons.httpclient.methods.multipart.FilePart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\class-use\FilePart.html
#define IDH_1189	1189	; Uses of Class org.apache.commons.httpclient.methods.multipart.FilePartSource (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\methods\multipart\class-use\FilePartSource.html
#define IDH_1190	1190	; Uses of Class org.apache.commons.httpclient.methods.multipart.MultipartRequestEntity (HttpClient 3.1 apidocs\org\apache\commons\httpclient\methods\multipart\class-use\MultipartRequestEntity.html
#define IDH_1191	1191	; Uses of Class org.apache.commons.httpclient.methods.multipart.Part (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\class-use\Part.html
#define IDH_1192	1192	; Uses of Class org.apache.commons.httpclient.methods.multipart.PartBase (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\class-use\PartBase.html
#define IDH_1194	1194	; Uses of Class org.apache.commons.httpclient.methods.multipart.StringPart (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\methods\multipart\class-use\StringPart.html
#define IDH_1193	1193	; Uses of Interface org.apache.commons.httpclient.methods.multipart.PartSource (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\methods\multipart\class-use\PartSource.html
#define IDH_1234	1234	; DefaultHttpParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\DefaultHttpParams.html
#define IDH_1235	1235	; DefaultHttpParamsFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\DefaultHttpParamsFactory.html
#define IDH_1236	1236	; HostParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HostParams.html
#define IDH_1237	1237	; HttpClientParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpClientParams.html
#define IDH_1238	1238	; HttpConnectionManagerParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpConnectionManagerParams.html
#define IDH_1239	1239	; HttpConnectionParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpConnectionParams.html
#define IDH_1240	1240	; HttpMethodParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpMethodParams.html
#define IDH_1241	1241	; HttpParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpParams.html
#define IDH_1242	1242	; HttpParamsFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\HttpParamsFactory.html
#define IDH_1243	1243	; org.apache.commons.httpclient.params (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\package-frame.html
#define IDH_1244	1244	; org.apache.commons.httpclient.params (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\package-summary.html
#define IDH_1245	1245	; org.apache.commons.httpclient.params Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\package-tree.html
#define IDH_1246	1246	; Uses of Package org.apache.commons.httpclient.params (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\package-use.html
#define IDH_1225	1225	; Uses of Class org.apache.commons.httpclient.params.DefaultHttpParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\DefaultHttpParams.html
#define IDH_1226	1226	; Uses of Class org.apache.commons.httpclient.params.DefaultHttpParamsFactory (HttpClient 3.1-alpha1 A apidocs\org\apache\commons\httpclient\params\class-use\DefaultHttpParamsFactory.html
#define IDH_1227	1227	; Uses of Class org.apache.commons.httpclient.params.HostParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HostParams.html
#define IDH_1228	1228	; Uses of Class org.apache.commons.httpclient.params.HttpClientParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HttpClientParams.html
#define IDH_1229	1229	; Uses of Class org.apache.commons.httpclient.params.HttpConnectionManagerParams (HttpClient 3.1-alpha apidocs\org\apache\commons\httpclient\params\class-use\HttpConnectionManagerParams.html
#define IDH_1230	1230	; Uses of Class org.apache.commons.httpclient.params.HttpConnectionParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HttpConnectionParams.html
#define IDH_1231	1231	; Uses of Class org.apache.commons.httpclient.params.HttpMethodParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HttpMethodParams.html
#define IDH_1232	1232	; Uses of Interface org.apache.commons.httpclient.params.HttpParams (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HttpParams.html
#define IDH_1233	1233	; Uses of Interface org.apache.commons.httpclient.params.HttpParamsFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\params\class-use\HttpParamsFactory.html
#define IDH_1255	1255	; ControllerThreadSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\ControllerThreadSocketFactory.html
#define IDH_1256	1256	; ControllerThreadSocketFactory.SocketTask (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\ControllerThreadSocketFactory.SocketTask.html
#define IDH_1257	1257	; DefaultProtocolSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\DefaultProtocolSocketFactory.html
#define IDH_1258	1258	; org.apache.commons.httpclient.protocol (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\package-frame.html
#define IDH_1259	1259	; org.apache.commons.httpclient.protocol (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\package-summary.html
#define IDH_1260	1260	; org.apache.commons.httpclient.protocol Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\package-tree.html
#define IDH_1262	1262	; Protocol (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\Protocol.html
#define IDH_1263	1263	; ProtocolSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\ProtocolSocketFactory.html
#define IDH_1264	1264	; ReflectionSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\ReflectionSocketFactory.html
#define IDH_1265	1265	; SecureProtocolSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\SecureProtocolSocketFactory.html
#define IDH_1266	1266	; SSLProtocolSocketFactory (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\SSLProtocolSocketFactory.html
#define IDH_1261	1261	; Uses of Package org.apache.commons.httpclient.protocol (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\package-use.html
#define IDH_1247	1247	; Uses of Class org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory (HttpClient 3.1-a apidocs\org\apache\commons\httpclient\protocol\class-use\ControllerThreadSocketFactory.html
#define IDH_1248	1248	; Uses of Class org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory.SocketTask (HttpC apidocs\org\apache\commons\httpclient\protocol\class-use\ControllerThreadSocketFactory.SocketTask.html
#define IDH_1249	1249	; Uses of Class org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory (HttpClient 3.1-al apidocs\org\apache\commons\httpclient\protocol\class-use\DefaultProtocolSocketFactory.html
#define IDH_1250	1250	; Uses of Class org.apache.commons.httpclient.protocol.Protocol (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\protocol\class-use\Protocol.html
#define IDH_1252	1252	; Uses of Class org.apache.commons.httpclient.protocol.ReflectionSocketFactory (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\protocol\class-use\ReflectionSocketFactory.html
#define IDH_1254	1254	; Uses of Class org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\protocol\class-use\SSLProtocolSocketFactory.html
#define IDH_1251	1251	; Uses of Interface org.apache.commons.httpclient.protocol.ProtocolSocketFactory (HttpClient 3.1-alpha apidocs\org\apache\commons\httpclient\protocol\class-use\ProtocolSocketFactory.html
#define IDH_1253	1253	; Uses of Interface org.apache.commons.httpclient.protocol.SecureProtocolSocketFactory (HttpClient 3.1 apidocs\org\apache\commons\httpclient\protocol\class-use\SecureProtocolSocketFactory.html
#define IDH_1294	1294	; DateParseException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\DateParseException.html
#define IDH_1295	1295	; DateParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\DateParser.html
#define IDH_1296	1296	; DateUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\DateUtil.html
#define IDH_1297	1297	; EncodingUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\EncodingUtil.html
#define IDH_1298	1298	; ExceptionUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\ExceptionUtil.html
#define IDH_1299	1299	; HttpURLConnection (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\HttpURLConnection.html
#define IDH_1300	1300	; IdleConnectionHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\IdleConnectionHandler.html
#define IDH_1301	1301	; IdleConnectionTimeoutThread (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\IdleConnectionTimeoutThread.html
#define IDH_1302	1302	; LangUtils (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\LangUtils.html
#define IDH_1303	1303	; org.apache.commons.httpclient.util (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\package-frame.html
#define IDH_1304	1304	; org.apache.commons.httpclient.util (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\package-summary.html
#define IDH_1305	1305	; org.apache.commons.httpclient.util Class Hierarchy (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\package-tree.html
#define IDH_1307	1307	; ParameterFormatter (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\ParameterFormatter.html
#define IDH_1308	1308	; ParameterParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\ParameterParser.html
#define IDH_1309	1309	; TimeoutController (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\TimeoutController.html
#define IDH_1310	1310	; TimeoutController.TimeoutException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\TimeoutController.TimeoutException.html
#define IDH_1312	1312	; URIUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\URIUtil.html
#define IDH_1311	1311	; URIUtil.Coder (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\URIUtil.Coder.html
#define IDH_1306	1306	; Uses of Package org.apache.commons.httpclient.util (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\package-use.html
#define IDH_1279	1279	; Uses of Class org.apache.commons.httpclient.util.DateParseException (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\DateParseException.html
#define IDH_1280	1280	; Uses of Class org.apache.commons.httpclient.util.DateParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\DateParser.html
#define IDH_1281	1281	; Uses of Class org.apache.commons.httpclient.util.DateUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\DateUtil.html
#define IDH_1282	1282	; Uses of Class org.apache.commons.httpclient.util.EncodingUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\EncodingUtil.html
#define IDH_1283	1283	; Uses of Class org.apache.commons.httpclient.util.ExceptionUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\ExceptionUtil.html
#define IDH_1284	1284	; Uses of Class org.apache.commons.httpclient.util.HttpURLConnection (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\HttpURLConnection.html
#define IDH_1285	1285	; Uses of Class org.apache.commons.httpclient.util.IdleConnectionHandler (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\IdleConnectionHandler.html
#define IDH_1286	1286	; Uses of Class org.apache.commons.httpclient.util.IdleConnectionTimeoutThread (HttpClient 3.1-alpha1 apidocs\org\apache\commons\httpclient\util\class-use\IdleConnectionTimeoutThread.html
#define IDH_1287	1287	; Uses of Class org.apache.commons.httpclient.util.LangUtils (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\LangUtils.html
#define IDH_1288	1288	; Uses of Class org.apache.commons.httpclient.util.ParameterFormatter (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\ParameterFormatter.html
#define IDH_1289	1289	; Uses of Class org.apache.commons.httpclient.util.ParameterParser (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\ParameterParser.html
#define IDH_1290	1290	; Uses of Class org.apache.commons.httpclient.util.TimeoutController (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\TimeoutController.html
#define IDH_1291	1291	; Uses of Class org.apache.commons.httpclient.util.TimeoutController.TimeoutException (HttpClient 3.1- apidocs\org\apache\commons\httpclient\util\class-use\TimeoutController.TimeoutException.html
#define IDH_1293	1293	; Uses of Class org.apache.commons.httpclient.util.URIUtil (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\URIUtil.html
#define IDH_1292	1292	; Uses of Class org.apache.commons.httpclient.util.URIUtil.Coder (HttpClient 3.1-alpha1 API) apidocs\org\apache\commons\httpclient\util\class-use\URIUtil.Coder.html
#define IDH_1340	1340	; HttpClient - methods\delete.html
#define IDH_1341	1341	; HttpClient - methods\get.html
#define IDH_1342	1342	; HttpClient - methods\head.html
#define IDH_1343	1343	; HttpClient - methods\multipartpost.html
#define IDH_1344	1344	; HttpClient - methods\options.html
#define IDH_1345	1345	; HttpClient - methods\post.html
#define IDH_1346	1346	; HttpClient - methods\put.html
#define IDH_1347	1347	; HttpClient - methods\trace.html
#define IDH_1364	1364	; All Classes xref\allclasses-frame.html
#define IDH_1365	1365	; HttpClient 3.1-alpha1 Reference xref\index.html
#define IDH_1520	1520	; HttpClient 3.1-alpha1 Reference xref\overview-frame.html
#define IDH_1521	1521	; HttpClient 3.1-alpha1 Reference xref\overview-summary.html
#define IDH_1388	1388	; AutoCloseInputStream xref xref\org\apache\commons\httpclient\AutoCloseInputStream.html
#define IDH_1389	1389	; ChunkedInputStream xref xref\org\apache\commons\httpclient\ChunkedInputStream.html
#define IDH_1390	1390	; ChunkedOutputStream xref xref\org\apache\commons\httpclient\ChunkedOutputStream.html
#define IDH_1391	1391	; CircularRedirectException xref xref\org\apache\commons\httpclient\CircularRedirectException.html
#define IDH_1392	1392	; ConnectionPoolTimeoutException xref xref\org\apache\commons\httpclient\ConnectionPoolTimeoutException.html
#define IDH_1393	1393	; ConnectMethod xref xref\org\apache\commons\httpclient\ConnectMethod.html
#define IDH_1394	1394	; ConnectTimeoutException xref xref\org\apache\commons\httpclient\ConnectTimeoutException.html
#define IDH_1395	1395	; ContentLengthInputStream xref xref\org\apache\commons\httpclient\ContentLengthInputStream.html
#define IDH_1411	1411	; Cookie xref xref\org\apache\commons\httpclient\Cookie.html
#define IDH_1412	1412	; Credentials xref xref\org\apache\commons\httpclient\Credentials.html
#define IDH_1413	1413	; DefaultHttpMethodRetryHandler xref xref\org\apache\commons\httpclient\DefaultHttpMethodRetryHandler.html
#define IDH_1414	1414	; DefaultMethodRetryHandler xref xref\org\apache\commons\httpclient\DefaultMethodRetryHandler.html
#define IDH_1415	1415	; Header xref xref\org\apache\commons\httpclient\Header.html
#define IDH_1416	1416	; HeaderElement xref xref\org\apache\commons\httpclient\HeaderElement.html
#define IDH_1417	1417	; HeaderGroup xref xref\org\apache\commons\httpclient\HeaderGroup.html
#define IDH_1418	1418	; HostConfiguration xref xref\org\apache\commons\httpclient\HostConfiguration.html
#define IDH_1471	1471	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\package-summary.html
#define IDH_1470	1470	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient xref\org\apache\commons\httpclient\package-frame.html
#define IDH_1419	1419	; HttpClient xref xref\org\apache\commons\httpclient\HttpClient.html
#define IDH_1420	1420	; HttpClientError xref xref\org\apache\commons\httpclient\HttpClientError.html
#define IDH_1421	1421	; HttpConnection xref xref\org\apache\commons\httpclient\HttpConnection.html
#define IDH_1422	1422	; HttpConnectionManager xref xref\org\apache\commons\httpclient\HttpConnectionManager.html
#define IDH_1423	1423	; HttpConstants xref xref\org\apache\commons\httpclient\HttpConstants.html
#define IDH_1424	1424	; HttpException xref xref\org\apache\commons\httpclient\HttpException.html
#define IDH_1425	1425	; HttpHost xref xref\org\apache\commons\httpclient\HttpHost.html
#define IDH_1426	1426	; HttpMethod xref xref\org\apache\commons\httpclient\HttpMethod.html
#define IDH_1427	1427	; HttpMethodBase xref xref\org\apache\commons\httpclient\HttpMethodBase.html
#define IDH_1428	1428	; HttpMethodDirector xref xref\org\apache\commons\httpclient\HttpMethodDirector.html
#define IDH_1429	1429	; HttpMethodRetryHandler xref xref\org\apache\commons\httpclient\HttpMethodRetryHandler.html
#define IDH_1430	1430	; HttpParser xref xref\org\apache\commons\httpclient\HttpParser.html
#define IDH_1431	1431	; HttpRecoverableException xref xref\org\apache\commons\httpclient\HttpRecoverableException.html
#define IDH_1432	1432	; HttpState xref xref\org\apache\commons\httpclient\HttpState.html
#define IDH_1433	1433	; HttpStatus xref xref\org\apache\commons\httpclient\HttpStatus.html
#define IDH_1434	1434	; HttpsURL xref xref\org\apache\commons\httpclient\HttpsURL.html
#define IDH_1435	1435	; HttpURL xref xref\org\apache\commons\httpclient\HttpURL.html
#define IDH_1436	1436	; HttpVersion xref xref\org\apache\commons\httpclient\HttpVersion.html
#define IDH_1437	1437	; InvalidRedirectLocationException xref xref\org\apache\commons\httpclient\InvalidRedirectLocationException.html
#define IDH_1438	1438	; MethodRetryHandler xref xref\org\apache\commons\httpclient\MethodRetryHandler.html
#define IDH_1466	1466	; MultiThreadedHttpConnectionManager xref xref\org\apache\commons\httpclient\MultiThreadedHttpConnectionManager.html
#define IDH_1467	1467	; NameValuePair xref xref\org\apache\commons\httpclient\NameValuePair.html
#define IDH_1468	1468	; NoHttpResponseException xref xref\org\apache\commons\httpclient\NoHttpResponseException.html
#define IDH_1469	1469	; NTCredentials xref xref\org\apache\commons\httpclient\NTCredentials.html
#define IDH_1492	1492	; ProtocolException xref xref\org\apache\commons\httpclient\ProtocolException.html
#define IDH_1493	1493	; ProxyClient xref xref\org\apache\commons\httpclient\ProxyClient.html
#define IDH_1494	1494	; ProxyHost xref xref\org\apache\commons\httpclient\ProxyHost.html
#define IDH_1495	1495	; RedirectException xref xref\org\apache\commons\httpclient\RedirectException.html
#define IDH_1496	1496	; ResponseConsumedWatcher xref xref\org\apache\commons\httpclient\ResponseConsumedWatcher.html
#define IDH_1497	1497	; SimpleHttpConnectionManager xref xref\org\apache\commons\httpclient\SimpleHttpConnectionManager.html
#define IDH_1498	1498	; StatusLine xref xref\org\apache\commons\httpclient\StatusLine.html
#define IDH_1499	1499	; URI xref xref\org\apache\commons\httpclient\URI.html
#define IDH_1500	1500	; URIException xref xref\org\apache\commons\httpclient\URIException.html
#define IDH_1501	1501	; UsernamePasswordCredentials xref xref\org\apache\commons\httpclient\UsernamePasswordCredentials.html
#define IDH_1517	1517	; Wire xref xref\org\apache\commons\httpclient\Wire.html
#define IDH_1518	1518	; WireLogInputStream xref xref\org\apache\commons\httpclient\WireLogInputStream.html
#define IDH_1519	1519	; WireLogOutputStream xref xref\org\apache\commons\httpclient\WireLogOutputStream.html
#define IDH_1366	1366	; AuthChallengeException xref xref\org\apache\commons\httpclient\auth\AuthChallengeException.html
#define IDH_1367	1367	; AuthChallengeParser xref xref\org\apache\commons\httpclient\auth\AuthChallengeParser.html
#define IDH_1368	1368	; AuthChallengeProcessor xref xref\org\apache\commons\httpclient\auth\AuthChallengeProcessor.html
#define IDH_1369	1369	; AuthenticationException xref xref\org\apache\commons\httpclient\auth\AuthenticationException.html
#define IDH_1370	1370	; AuthPolicy xref xref\org\apache\commons\httpclient\auth\AuthPolicy.html
#define IDH_1371	1371	; AuthScheme xref xref\org\apache\commons\httpclient\auth\AuthScheme.html
#define IDH_1372	1372	; AuthSchemeBase xref xref\org\apache\commons\httpclient\auth\AuthSchemeBase.html
#define IDH_1373	1373	; AuthScope xref xref\org\apache\commons\httpclient\auth\AuthScope.html
#define IDH_1374	1374	; AuthState xref xref\org\apache\commons\httpclient\auth\AuthState.html
#define IDH_1375	1375	; BasicScheme xref xref\org\apache\commons\httpclient\auth\BasicScheme.html
#define IDH_1376	1376	; CredentialsNotAvailableException xref xref\org\apache\commons\httpclient\auth\CredentialsNotAvailableException.html
#define IDH_1377	1377	; CredentialsProvider xref xref\org\apache\commons\httpclient\auth\CredentialsProvider.html
#define IDH_1378	1378	; DigestScheme xref xref\org\apache\commons\httpclient\auth\DigestScheme.html
#define IDH_1379	1379	; HttpAuthenticator xref xref\org\apache\commons\httpclient\auth\HttpAuthenticator.html
#define IDH_1380	1380	; HttpAuthRealm xref xref\org\apache\commons\httpclient\auth\HttpAuthRealm.html
#define IDH_1386	1386	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\auth\package-summary.html
#define IDH_1385	1385	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.auth xref\org\apache\commons\httpclient\auth\package-frame.html
#define IDH_1381	1381	; InvalidCredentialsException xref xref\org\apache\commons\httpclient\auth\InvalidCredentialsException.html
#define IDH_1382	1382	; MalformedChallengeException xref xref\org\apache\commons\httpclient\auth\MalformedChallengeException.html
#define IDH_1383	1383	; NTLM xref xref\org\apache\commons\httpclient\auth\NTLM.html
#define IDH_1384	1384	; NTLMScheme xref xref\org\apache\commons\httpclient\auth\NTLMScheme.html
#define IDH_1387	1387	; RFC2617Scheme xref xref\org\apache\commons\httpclient\auth\RFC2617Scheme.html
#define IDH_1396	1396	; Cookie2 xref xref\org\apache\commons\httpclient\cookie\Cookie2.html
#define IDH_1397	1397	; CookieAttributeHandler xref xref\org\apache\commons\httpclient\cookie\CookieAttributeHandler.html
#define IDH_1398	1398	; CookieOrigin xref xref\org\apache\commons\httpclient\cookie\CookieOrigin.html
#define IDH_1399	1399	; CookiePathComparator xref xref\org\apache\commons\httpclient\cookie\CookiePathComparator.html
#define IDH_1400	1400	; CookiePolicy xref xref\org\apache\commons\httpclient\cookie\CookiePolicy.html
#define IDH_1401	1401	; CookieSpec xref xref\org\apache\commons\httpclient\cookie\CookieSpec.html
#define IDH_1402	1402	; CookieSpecBase xref xref\org\apache\commons\httpclient\cookie\CookieSpecBase.html
#define IDH_1403	1403	; CookieVersionSupport xref xref\org\apache\commons\httpclient\cookie\CookieVersionSupport.html
#define IDH_1408	1408	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\cookie\package-summary.html
#define IDH_1407	1407	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.cookie xref\org\apache\commons\httpclient\cookie\package-frame.html
#define IDH_1404	1404	; IgnoreCookiesSpec xref xref\org\apache\commons\httpclient\cookie\IgnoreCookiesSpec.html
#define IDH_1405	1405	; MalformedCookieException xref xref\org\apache\commons\httpclient\cookie\MalformedCookieException.html
#define IDH_1406	1406	; NetscapeDraftSpec xref xref\org\apache\commons\httpclient\cookie\NetscapeDraftSpec.html
#define IDH_1409	1409	; RFC2109Spec xref xref\org\apache\commons\httpclient\cookie\RFC2109Spec.html
#define IDH_1410	1410	; RFC2965Spec xref xref\org\apache\commons\httpclient\cookie\RFC2965Spec.html
#define IDH_1439	1439	; ByteArrayRequestEntity xref xref\org\apache\commons\httpclient\methods\ByteArrayRequestEntity.html
#define IDH_1440	1440	; DeleteMethod xref xref\org\apache\commons\httpclient\methods\DeleteMethod.html
#define IDH_1441	1441	; EntityEnclosingMethod xref xref\org\apache\commons\httpclient\methods\EntityEnclosingMethod.html
#define IDH_1442	1442	; ExpectContinueMethod xref xref\org\apache\commons\httpclient\methods\ExpectContinueMethod.html
#define IDH_1443	1443	; FileRequestEntity xref xref\org\apache\commons\httpclient\methods\FileRequestEntity.html
#define IDH_1444	1444	; GetMethod xref xref\org\apache\commons\httpclient\methods\GetMethod.html
#define IDH_1445	1445	; HeadMethod xref xref\org\apache\commons\httpclient\methods\HeadMethod.html
#define IDH_1460	1460	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\methods\package-summary.html
#define IDH_1459	1459	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.methods xref\org\apache\commons\httpclient\methods\package-frame.html
#define IDH_1446	1446	; InputStreamRequestEntity xref xref\org\apache\commons\httpclient\methods\InputStreamRequestEntity.html
#define IDH_1457	1457	; MultipartPostMethod xref xref\org\apache\commons\httpclient\methods\MultipartPostMethod.html
#define IDH_1458	1458	; OptionsMethod xref xref\org\apache\commons\httpclient\methods\OptionsMethod.html
#define IDH_1461	1461	; PostMethod xref xref\org\apache\commons\httpclient\methods\PostMethod.html
#define IDH_1462	1462	; PutMethod xref xref\org\apache\commons\httpclient\methods\PutMethod.html
#define IDH_1463	1463	; RequestEntity xref xref\org\apache\commons\httpclient\methods\RequestEntity.html
#define IDH_1464	1464	; StringRequestEntity xref xref\org\apache\commons\httpclient\methods\StringRequestEntity.html
#define IDH_1465	1465	; TraceMethod xref xref\org\apache\commons\httpclient\methods\TraceMethod.html
#define IDH_1447	1447	; ByteArrayPartSource xref xref\org\apache\commons\httpclient\methods\multipart\ByteArrayPartSource.html
#define IDH_1448	1448	; FilePart xref xref\org\apache\commons\httpclient\methods\multipart\FilePart.html
#define IDH_1449	1449	; FilePartSource xref xref\org\apache\commons\httpclient\methods\multipart\FilePartSource.html
#define IDH_1452	1452	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\methods\multipart\package-summary.html
#define IDH_1451	1451	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.methods.multipart xref\org\apache\commons\httpclient\methods\multipart\package-frame.html
#define IDH_1450	1450	; MultipartRequestEntity xref xref\org\apache\commons\httpclient\methods\multipart\MultipartRequestEntity.html
#define IDH_1453	1453	; Part xref xref\org\apache\commons\httpclient\methods\multipart\Part.html
#define IDH_1454	1454	; PartBase xref xref\org\apache\commons\httpclient\methods\multipart\PartBase.html
#define IDH_1455	1455	; PartSource xref xref\org\apache\commons\httpclient\methods\multipart\PartSource.html
#define IDH_1456	1456	; StringPart xref xref\org\apache\commons\httpclient\methods\multipart\StringPart.html
#define IDH_1472	1472	; DefaultHttpParams xref xref\org\apache\commons\httpclient\params\DefaultHttpParams.html
#define IDH_1473	1473	; DefaultHttpParamsFactory xref xref\org\apache\commons\httpclient\params\DefaultHttpParamsFactory.html
#define IDH_1474	1474	; HostParams xref xref\org\apache\commons\httpclient\params\HostParams.html
#define IDH_1482	1482	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\params\package-summary.html
#define IDH_1481	1481	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.params xref\org\apache\commons\httpclient\params\package-frame.html
#define IDH_1475	1475	; HttpClientParams xref xref\org\apache\commons\httpclient\params\HttpClientParams.html
#define IDH_1476	1476	; HttpConnectionManagerParams xref xref\org\apache\commons\httpclient\params\HttpConnectionManagerParams.html
#define IDH_1477	1477	; HttpConnectionParams xref xref\org\apache\commons\httpclient\params\HttpConnectionParams.html
#define IDH_1478	1478	; HttpMethodParams xref xref\org\apache\commons\httpclient\params\HttpMethodParams.html
#define IDH_1479	1479	; HttpParams xref xref\org\apache\commons\httpclient\params\HttpParams.html
#define IDH_1480	1480	; HttpParamsFactory xref xref\org\apache\commons\httpclient\params\HttpParamsFactory.html
#define IDH_1483	1483	; ControllerThreadSocketFactory xref xref\org\apache\commons\httpclient\protocol\ControllerThreadSocketFactory.html
#define IDH_1484	1484	; DefaultProtocolSocketFactory xref xref\org\apache\commons\httpclient\protocol\DefaultProtocolSocketFactory.html
#define IDH_1486	1486	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\protocol\package-summary.html
#define IDH_1485	1485	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.protocol xref\org\apache\commons\httpclient\protocol\package-frame.html
#define IDH_1487	1487	; Protocol xref xref\org\apache\commons\httpclient\protocol\Protocol.html
#define IDH_1488	1488	; ProtocolSocketFactory xref xref\org\apache\commons\httpclient\protocol\ProtocolSocketFactory.html
#define IDH_1489	1489	; ReflectionSocketFactory xref xref\org\apache\commons\httpclient\protocol\ReflectionSocketFactory.html
#define IDH_1490	1490	; SecureProtocolSocketFactory xref xref\org\apache\commons\httpclient\protocol\SecureProtocolSocketFactory.html
#define IDH_1491	1491	; SSLProtocolSocketFactory xref xref\org\apache\commons\httpclient\protocol\SSLProtocolSocketFactory.html
#define IDH_1502	1502	; DateParseException xref xref\org\apache\commons\httpclient\util\DateParseException.html
#define IDH_1503	1503	; DateParser xref xref\org\apache\commons\httpclient\util\DateParser.html
#define IDH_1504	1504	; DateUtil xref xref\org\apache\commons\httpclient\util\DateUtil.html
#define IDH_1505	1505	; EncodingUtil xref xref\org\apache\commons\httpclient\util\EncodingUtil.html
#define IDH_1506	1506	; ExceptionUtil xref xref\org\apache\commons\httpclient\util\ExceptionUtil.html
#define IDH_1512	1512	; HttpClient 3.1-alpha1 Reference Package xref\org\apache\commons\httpclient\util\package-summary.html
#define IDH_1511	1511	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.util xref\org\apache\commons\httpclient\util\package-frame.html
#define IDH_1507	1507	; HttpURLConnection xref xref\org\apache\commons\httpclient\util\HttpURLConnection.html
#define IDH_1508	1508	; IdleConnectionHandler xref xref\org\apache\commons\httpclient\util\IdleConnectionHandler.html
#define IDH_1509	1509	; IdleConnectionTimeoutThread xref xref\org\apache\commons\httpclient\util\IdleConnectionTimeoutThread.html
#define IDH_1510	1510	; LangUtils xref xref\org\apache\commons\httpclient\util\LangUtils.html
#define IDH_1513	1513	; ParameterFormatter xref xref\org\apache\commons\httpclient\util\ParameterFormatter.html
#define IDH_1514	1514	; ParameterParser xref xref\org\apache\commons\httpclient\util\ParameterParser.html
#define IDH_1515	1515	; TimeoutController xref xref\org\apache\commons\httpclient\util\TimeoutController.html
#define IDH_1516	1516	; URIUtil xref xref\org\apache\commons\httpclient\util\URIUtil.html
#define IDH_1522	1522	; All Classes xref-test\allclasses-frame.html
#define IDH_1523	1523	; HttpClient 3.1-alpha1 Reference xref-test\index.html
#define IDH_1638	1638	; HttpClient 3.1-alpha1 Reference xref-test\overview-frame.html
#define IDH_1639	1639	; HttpClient 3.1-alpha1 Reference xref-test\overview-summary.html
#define IDH_1524	1524	; AccessibleHttpConnectionManager xref xref-test\org\apache\commons\httpclient\AccessibleHttpConnectionManager.html
#define IDH_1548	1548	; EchoService xref xref-test\org\apache\commons\httpclient\EchoService.html
#define IDH_1549	1549	; ExecuteMethodThread xref xref-test\org\apache\commons\httpclient\ExecuteMethodThread.html
#define IDH_1550	1550	; FakeHttpMethod xref xref-test\org\apache\commons\httpclient\FakeHttpMethod.html
#define IDH_1551	1551	; FeedbackService xref xref-test\org\apache\commons\httpclient\FeedbackService.html
#define IDH_1557	1557	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\package-summary.html
#define IDH_1556	1556	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient xref-test\org\apache\commons\httpclient\package-frame.html
#define IDH_1552	1552	; HttpClientTestBase xref xref-test\org\apache\commons\httpclient\HttpClientTestBase.html
#define IDH_1553	1553	; NoHostHttpConnectionManager xref xref-test\org\apache\commons\httpclient\NoHostHttpConnectionManager.html
#define IDH_1554	1554	; NoncompliantHeadMethod xref xref-test\org\apache\commons\httpclient\NoncompliantHeadMethod.html
#define IDH_1555	1555	; NoncompliantPostMethod xref xref-test\org\apache\commons\httpclient\NoncompliantPostMethod.html
#define IDH_1563	1563	; ProxyTestDecorator xref xref-test\org\apache\commons\httpclient\ProxyTestDecorator.html
#define IDH_1593	1593	; TestAll xref xref-test\org\apache\commons\httpclient\TestAll.html
#define IDH_1594	1594	; TestBadContentLength xref xref-test\org\apache\commons\httpclient\TestBadContentLength.html
#define IDH_1595	1595	; TestConnectionPersistence xref xref-test\org\apache\commons\httpclient\TestConnectionPersistence.html
#define IDH_1596	1596	; TestCredentials xref xref-test\org\apache\commons\httpclient\TestCredentials.html
#define IDH_1597	1597	; TestEffectiveHttpVersion xref xref-test\org\apache\commons\httpclient\TestEffectiveHttpVersion.html
#define IDH_1598	1598	; TestEntityEnclosingMethod xref xref-test\org\apache\commons\httpclient\TestEntityEnclosingMethod.html
#define IDH_1599	1599	; TestEquals xref xref-test\org\apache\commons\httpclient\TestEquals.html
#define IDH_1600	1600	; TestExceptions xref xref-test\org\apache\commons\httpclient\TestExceptions.html
#define IDH_1601	1601	; TestHeader xref xref-test\org\apache\commons\httpclient\TestHeader.html
#define IDH_1602	1602	; TestHeaderElement xref xref-test\org\apache\commons\httpclient\TestHeaderElement.html
#define IDH_1603	1603	; TestHeaderOps xref xref-test\org\apache\commons\httpclient\TestHeaderOps.html
#define IDH_1604	1604	; TestHostConfiguration xref xref-test\org\apache\commons\httpclient\TestHostConfiguration.html
#define IDH_1605	1605	; TestHttpConnection xref xref-test\org\apache\commons\httpclient\TestHttpConnection.html
#define IDH_1606	1606	; TestHttpConnectionManager xref xref-test\org\apache\commons\httpclient\TestHttpConnectionManager.html
#define IDH_1607	1607	; TestHttpMethodFundamentals xref xref-test\org\apache\commons\httpclient\TestHttpMethodFundamentals.html
#define IDH_1608	1608	; TestHttpParser xref xref-test\org\apache\commons\httpclient\TestHttpParser.html
#define IDH_1609	1609	; TestHttps xref xref-test\org\apache\commons\httpclient\TestHttps.html
#define IDH_1610	1610	; TestHttpState xref xref-test\org\apache\commons\httpclient\TestHttpState.html
#define IDH_1611	1611	; TestHttpStatus xref xref-test\org\apache\commons\httpclient\TestHttpStatus.html
#define IDH_1612	1612	; TestHttpVersion xref xref-test\org\apache\commons\httpclient\TestHttpVersion.html
#define IDH_1613	1613	; TestIdleConnectionTimeout xref xref-test\org\apache\commons\httpclient\TestIdleConnectionTimeout.html
#define IDH_1614	1614	; TestMethodAbort xref xref-test\org\apache\commons\httpclient\TestMethodAbort.html
#define IDH_1615	1615	; TestMethodCharEncoding xref xref-test\org\apache\commons\httpclient\TestMethodCharEncoding.html
#define IDH_1616	1616	; TestMultipartPost xref xref-test\org\apache\commons\httpclient\TestMultipartPost.html
#define IDH_1617	1617	; TestNoHost xref xref-test\org\apache\commons\httpclient\TestNoHost.html
#define IDH_1618	1618	; TestNoncompliant xref xref-test\org\apache\commons\httpclient\TestNoncompliant.html
#define IDH_1619	1619	; TestNVP xref xref-test\org\apache\commons\httpclient\TestNVP.html
#define IDH_1620	1620	; TestParameterFormatter xref xref-test\org\apache\commons\httpclient\TestParameterFormatter.html
#define IDH_1621	1621	; TestParameterParser xref xref-test\org\apache\commons\httpclient\TestParameterParser.html
#define IDH_1622	1622	; TestPartsNoHost xref xref-test\org\apache\commons\httpclient\TestPartsNoHost.html
#define IDH_1623	1623	; TestPostMethod xref xref-test\org\apache\commons\httpclient\TestPostMethod.html
#define IDH_1624	1624	; TestPostParameterEncoding xref xref-test\org\apache\commons\httpclient\TestPostParameterEncoding.html
#define IDH_1625	1625	; TestProxy xref xref-test\org\apache\commons\httpclient\TestProxy.html
#define IDH_1626	1626	; TestProxyWithRedirect xref xref-test\org\apache\commons\httpclient\TestProxyWithRedirect.html
#define IDH_1627	1627	; TestQueryParameters xref xref-test\org\apache\commons\httpclient\TestQueryParameters.html
#define IDH_1628	1628	; TestRedirects xref xref-test\org\apache\commons\httpclient\TestRedirects.html
#define IDH_1629	1629	; TestRequestHeaders xref xref-test\org\apache\commons\httpclient\TestRequestHeaders.html
#define IDH_1630	1630	; TestRequestLine xref xref-test\org\apache\commons\httpclient\TestRequestLine.html
#define IDH_1631	1631	; TestResponseHeaders xref xref-test\org\apache\commons\httpclient\TestResponseHeaders.html
#define IDH_1632	1632	; TestStatusLine xref xref-test\org\apache\commons\httpclient\TestStatusLine.html
#define IDH_1633	1633	; TestStreams xref xref-test\org\apache\commons\httpclient\TestStreams.html
#define IDH_1634	1634	; TestURI xref xref-test\org\apache\commons\httpclient\TestURI.html
#define IDH_1635	1635	; TestURIUtil xref xref-test\org\apache\commons\httpclient\TestURIUtil.html
#define IDH_1636	1636	; TestURIUtil2 xref xref-test\org\apache\commons\httpclient\TestURIUtil2.html
#define IDH_1637	1637	; TestVirtualHost xref xref-test\org\apache\commons\httpclient\TestVirtualHost.html
#define IDH_1526	1526	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\auth\package-summary.html
#define IDH_1525	1525	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.auth xref-test\org\apache\commons\httpclient\auth\package-frame.html
#define IDH_1527	1527	; TestAuthAll xref xref-test\org\apache\commons\httpclient\auth\TestAuthAll.html
#define IDH_1528	1528	; TestBasicAuth xref xref-test\org\apache\commons\httpclient\auth\TestBasicAuth.html
#define IDH_1529	1529	; TestChallengeParser xref xref-test\org\apache\commons\httpclient\auth\TestChallengeParser.html
#define IDH_1530	1530	; TestChallengeProcessor xref xref-test\org\apache\commons\httpclient\auth\TestChallengeProcessor.html
#define IDH_1531	1531	; TestDigestAuth xref xref-test\org\apache\commons\httpclient\auth\TestDigestAuth.html
#define IDH_1532	1532	; TestNTLMAuth xref xref-test\org\apache\commons\httpclient\auth\TestNTLMAuth.html
#define IDH_1534	1534	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\cookie\package-summary.html
#define IDH_1533	1533	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.cookie xref-test\org\apache\commons\httpclient\cookie\package-frame.html
#define IDH_1535	1535	; TestCookie xref xref-test\org\apache\commons\httpclient\cookie\TestCookie.html
#define IDH_1536	1536	; TestCookie2 xref xref-test\org\apache\commons\httpclient\cookie\TestCookie2.html
#define IDH_1537	1537	; TestCookieAll xref xref-test\org\apache\commons\httpclient\cookie\TestCookieAll.html
#define IDH_1538	1538	; TestCookieBase xref xref-test\org\apache\commons\httpclient\cookie\TestCookieBase.html
#define IDH_1539	1539	; TestCookieCompatibilitySpec xref xref-test\org\apache\commons\httpclient\cookie\TestCookieCompatibilitySpec.html
#define IDH_1540	1540	; TestCookieIgnoreSpec xref xref-test\org\apache\commons\httpclient\cookie\TestCookieIgnoreSpec.html
#define IDH_1541	1541	; TestCookieNetscapeDraft xref xref-test\org\apache\commons\httpclient\cookie\TestCookieNetscapeDraft.html
#define IDH_1542	1542	; TestCookiePathComparator xref xref-test\org\apache\commons\httpclient\cookie\TestCookiePathComparator.html
#define IDH_1543	1543	; TestCookiePolicy xref xref-test\org\apache\commons\httpclient\cookie\TestCookiePolicy.html
#define IDH_1544	1544	; TestCookieRFC2109Spec xref xref-test\org\apache\commons\httpclient\cookie\TestCookieRFC2109Spec.html
#define IDH_1545	1545	; TestCookieRFC2965Spec xref xref-test\org\apache\commons\httpclient\cookie\TestCookieRFC2965Spec.html
#define IDH_1546	1546	; TestCookieVersionSupport xref xref-test\org\apache\commons\httpclient\cookie\TestCookieVersionSupport.html
#define IDH_1547	1547	; TestDateParser xref xref-test\org\apache\commons\httpclient\cookie\TestDateParser.html
#define IDH_1559	1559	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\params\package-summary.html
#define IDH_1558	1558	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.params xref-test\org\apache\commons\httpclient\params\package-frame.html
#define IDH_1560	1560	; TestHttpParams xref xref-test\org\apache\commons\httpclient\params\TestHttpParams.html
#define IDH_1561	1561	; TestParamsAll xref xref-test\org\apache\commons\httpclient\params\TestParamsAll.html
#define IDH_1562	1562	; TestSSLTunnelParams xref xref-test\org\apache\commons\httpclient\params\TestSSLTunnelParams.html
#define IDH_1564	1564	; AuthRequestHandler xref xref-test\org\apache\commons\httpclient\server\AuthRequestHandler.html
#define IDH_1565	1565	; ErrorResponse xref xref-test\org\apache\commons\httpclient\server\ErrorResponse.html
#define IDH_1571	1571	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\server\package-summary.html
#define IDH_1570	1570	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.server xref-test\org\apache\commons\httpclient\server\package-frame.html
#define IDH_1566	1566	; HttpRequestHandler xref xref-test\org\apache\commons\httpclient\server\HttpRequestHandler.html
#define IDH_1567	1567	; HttpRequestHandlerChain xref xref-test\org\apache\commons\httpclient\server\HttpRequestHandlerChain.html
#define IDH_1568	1568	; HttpService xref xref-test\org\apache\commons\httpclient\server\HttpService.html
#define IDH_1569	1569	; HttpServiceHandler xref xref-test\org\apache\commons\httpclient\server\HttpServiceHandler.html
#define IDH_1572	1572	; ProxyAuthRequestHandler xref xref-test\org\apache\commons\httpclient\server\ProxyAuthRequestHandler.html
#define IDH_1573	1573	; ProxyRequestHandler xref xref-test\org\apache\commons\httpclient\server\ProxyRequestHandler.html
#define IDH_1574	1574	; RequestLine xref xref-test\org\apache\commons\httpclient\server\RequestLine.html
#define IDH_1575	1575	; ResponseWriter xref xref-test\org\apache\commons\httpclient\server\ResponseWriter.html
#define IDH_1576	1576	; SimpleConnectionThread xref xref-test\org\apache\commons\httpclient\server\SimpleConnectionThread.html
#define IDH_1577	1577	; SimpleConnList xref xref-test\org\apache\commons\httpclient\server\SimpleConnList.html
#define IDH_1578	1578	; SimpleConnManager xref xref-test\org\apache\commons\httpclient\server\SimpleConnManager.html
#define IDH_1579	1579	; SimpleConnSet xref xref-test\org\apache\commons\httpclient\server\SimpleConnSet.html
#define IDH_1580	1580	; SimpleHost xref xref-test\org\apache\commons\httpclient\server\SimpleHost.html
#define IDH_1581	1581	; SimpleHttpServer xref xref-test\org\apache\commons\httpclient\server\SimpleHttpServer.html
#define IDH_1582	1582	; SimpleHttpServerConnection xref xref-test\org\apache\commons\httpclient\server\SimpleHttpServerConnection.html
#define IDH_1583	1583	; SimplePlainSocketFactory xref xref-test\org\apache\commons\httpclient\server\SimplePlainSocketFactory.html
#define IDH_1584	1584	; SimpleProxy xref xref-test\org\apache\commons\httpclient\server\SimpleProxy.html
#define IDH_1585	1585	; SimpleRequest xref xref-test\org\apache\commons\httpclient\server\SimpleRequest.html
#define IDH_1586	1586	; SimpleResponse xref xref-test\org\apache\commons\httpclient\server\SimpleResponse.html
#define IDH_1587	1587	; SimpleSocketFactory xref xref-test\org\apache\commons\httpclient\server\SimpleSocketFactory.html
#define IDH_1588	1588	; TransparentProxyRequestHandler xref xref-test\org\apache\commons\httpclient\server\TransparentProxyRequestHandler.html
#define IDH_1590	1590	; HttpClient 3.1-alpha1 Reference Package xref-test\org\apache\commons\httpclient\ssl\package-summary.html
#define IDH_1589	1589	; HttpClient 3.1-alpha1 Reference Package org.apache.commons.httpclient.ssl xref-test\org\apache\commons\httpclient\ssl\package-frame.html
#define IDH_1591	1591	; SimpleSSLSocketFactory xref xref-test\org\apache\commons\httpclient\ssl\SimpleSSLSocketFactory.html
#define IDH_1592	1592	; SimpleSSLTestProtocolSocketFactory xref xref-test\org\apache\commons\httpclient\ssl\SimpleSSLTestProtocolSocketFactory.html
